=== dalexeev/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="qualifiers" use="optional" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<xs:attribute type="xs:float" name="version" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dalexeev/godot/doc/classes/@GlobalScope.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="@GlobalScope" version="4.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Global scope constants and functions.
	</brief_description>
	<description>
		A list of global scope enumerated constants and built-in functions. This is all that resides in the globals, constants regarding error codes, keycodes, property hints, etc.
		Singletons are also documented here, since they can be accessed from anywhere.
		For the entries related to GDScript which can be accessed in any script see [@GDScript].
	</description>
	<tutorials>
		<link title="Random number generation">$DOCS_URL/tutorials/math/random_number_generation.html</link>
	</tutorials>
	<methods>
		<method name="abs">
			<return type="Variant" />
			<param index="0" name="x" type="Variant" />
			<description>
				Returns the absolute value of a [Variant] parameter [param x] (i.e. non-negative value). Supported types: [int], [float], [Vector2], [Vector2i], [Vector3], [Vector3i], [Vector4], [Vector4i].
				[codeblock]
				var a = abs(-1)
				# a is 1

				var b = abs(-1.2)
				# b is 1.2

				var c = abs(Vector2(-3.5, -4))
				# c is (3.5, 4)

				var d = abs(Vector2i(-5, -6))
				# d is (5, 6)

				var e = abs(Vector3(-7, 8.5, -3.8))
				# e is (7, 8.5, 3.8)

				var f = abs(Vector3i(-7, -8, -9))
				# f is (7, 8, 9)
				[/codeblock]
				[b]Note:[/b] For better type safety, use [method absf], [method absi], [method Vector2.abs], [method Vector2i.abs], [method Vector3.abs], [method Vector3i.abs], [method Vector4.abs], or [method Vector4i.abs].
			</description>
		</method>
		<method name="absf">
			<return type="float" />
			<param index="0" name="x" type="float" />
			<description>
				Returns the absolute value of float parameter [param x] (i.e. positive value).
				[codeblock]
				# a is 1.2
				var a = absf(-1.2)
				[/codeblock]
			</description>
		</method>
		<method name="absi">
			<return type="int" />
			<param index="0" name="x" type="int" />
			<description>
				Returns the absolute value of int parameter [param x] (i.e. positive value).
				[codeblock]
				# a is 1
				var a = absi(-1)
				[/codeblock]
			</description>
		</method>
		<method name="acos">
			<return type="float" />
			<param index="0" name="x" type="float" />
			<description>
				Returns the arc cosine of [param x] in radians. Use to get the angle of cosine [param x]. [param x] will be clamped between [code]-1.0[/code] and [code]1.0[/code] (inclusive), in order to prevent [method acos] from returning [constant @GDScript.NAN].
				[codeblock]
				# c is 0.523599 or 30 degrees if converted with rad_to_deg(c)
				var c = acos(0.866025)
				[/codeblock]
			</description>
		</method>
		<method name="asin">
			<return type="float" />
			<param index="0" name="x" type="float" />
			<description>
				Returns the arc sine of [param x] in radians. Use to get the angle of sine [param x]. [param x] will be clamped between [code]-1.0[/code] and [code]1.0[/code] (inclusive), in order to prevent [method asin] from returning [constant @GDScript.NAN].
				[codeblock]
				# s is 0.523599 or 30 degrees if converted with rad_to_deg(s)
				var s = asin(0.5)
				[/codeblock]
			</description>
		</method>
		<method name="atan">
			<return type="float" />
			<param index="0" name="x" type="float" />
			<description>
				Returns the arc tangent of [param x] in radians. Use it to get the angle from an angle's tangent in trigonometry.
				The method cannot know in which quadrant the angle should fall. See [method atan2] if you have both [code]y[/code] and [code]x[/code].
				[codeblock]
				var a = atan(0.5) # a is 0.463648
				[/codeblock]
				If [param x] is between [code]-PI / 2[/code] and [code]PI / 2[/code] (inclusive), [code]atan(tan(x))[/code] is equal to [param x].
			</description>
		</method>
		<method name="atan2">
			<return type="float" />
			<param index="0" name="y" type="float" />
			<param index="1" name="x" type="float" />
			<description>
				Returns the arc tangent of [code]y/x[/code] in radians. Use to get the angle of tangent [code]y/x[/code]. To compute the value, the method takes into account the sign of both arguments in order to determine the quadrant.
				Important note: The Y coordinate comes first, by convention.
				[codeblock]
				var a = atan2(0, -1) # a is 3.141593
				[/codeblock]
			</description>
		</method>
		<method name="bezier_derivative">
			<return type="float" />
			<param index="0" name="start" type="float" />
			<param index="1" name="control_1" type="float" />
			<param index="2" name="control_2" type="float" />
			<param index="3" name="end" type="float" />
			<param index="4" name="t" type="float" />
			<description>
				Returns the derivative at the given [param t] on a one-dimensional [url=https://en.wikipedia.org/wiki/B%C3%A9zier_curve]Bézier curve[/url] defined by the given [param control_1], [param control_2], and [param end] points.
			</description>
		</method>
		<method name="bezier_interpolate">
			<return type="float" />
			<param index="0" name="start" type="float" />
			<param index="1" name="control_1" type="float" />
			<param index="2" name="control_2" type="float" />
			<param index="3" name="end" type="float" />
			<param index="4" name="t" type="float" />
			<description>
				Returns the point at the given [param t] on a one-dimensional [url=https://en.wikipedia.org/wiki/B%C3%A9zier_curve]Bézier curve[/url] defined by the given [param control_1], [param control_2], and [param end] points.
			</description>
		</method>
		<method name="bytes_to_var">
			<return type="Variant" />
			<param index="0" name="bytes" type="PackedByteArray" />
			<description>
				Decodes a byte array back to a [Variant] value, without decoding objects.
				[b]Note:[/b] If you need object deserialization, see [method bytes_to_var_with_objects].
			</description>
		</method>
		<method name="bytes_to_var_with_objects">
			<return type="Variant" />
			<param index="0" name="bytes" type="PackedByteArray" />
			<description>
				Decodes a byte array back to a [Variant] value. Decoding objects is allowed.
				[b]Warning:[/b] Deserialized object can contain code which gets executed. Do not use this option if the serialized object comes from untrusted sources to avoid potential security threats (remote code execution).
			</description>
		</method>
		<method name="ceil">
			<return type="Variant" />
			<param index="0" name="x" type="Variant" />
			<description>
				Rounds [param x] upward (towards positive infinity), returning the smallest whole number that is not less than [param x]. Supported types: [int], [float], [Vector2], [Vector3], [Vector4].
				[codeblock]
				var i = ceil(1.45) # i is 2.0
				i = ceil(1.001)    # i is 2.0
				[/codeblock]
				See also [method floor], [method round], and [method snapped].
				[b]Note:[/b] For better type safety, use [method ceilf], [method ceili], [method Vector2.ceil], [method Vector3.ceil], or [method Vector4.ceil].
			</description>
		</method>
		<method name="ceilf">
			<return type="float" />
			<param index="0" name="x" type="float" />
			<description>
				Rounds [param x] upward (towards positive infinity), returning the smallest whole number that is not less than [param x].
				A type-safe version of [method ceil], returning a [float].
			</description>
		</method>
		<method name="ceili">
			<return type="int" />
			<param index="0" name="x" type="float" />
			<description>
				Rounds [param x] upward (towards positive infinity), returning the smallest whole number that is not less than [param x].
				A type-safe version of [method ceil], returning an [int].
			</description>
		</method>
		<method name="clamp">
			<return type="Variant" />
			<param index="0" name="value" type="Variant" />
			<param index="1" name="min" type="Variant" />
			<param index="2" name="max" type="Variant" />
			<description>
				Clamps the [param value], returning a [Variant] not less than [param min] and not more than [param max]. Supported types: [int], [float], [Vector2], [Vector2i], [Vector3], [Vector3i], [Vector4], [Vector4i].
				[codeblock]
				var a = clamp(-10, -1, 5)
				# a is -1

				var b = clamp(8.1, 0.9, 5.5)
				# b is 5.5

				var c = clamp(Vector2(-3.5, -4), Vector2(-3.2, -2), Vector2(2, 6.5))
				# c is (-3.2, -2)

				var d = clamp(Vector2i(7, 8), Vector2i(-3, -2), Vector2i(2, 6))
				# d is (2, 6)

				var e = clamp(Vector3(-7, 8.5, -3.8), Vector3(-3, -2, 5.4), Vector3(-2, 6, -4.1))
				# e is (-3, -2, 5.4)

				var f = clamp(Vector3i(-7, -8, -9), Vector3i(-1, 2, 3), Vector3i(-4, -5, -6))
				# f is (-4, -5, -6)
				[/codeblock]
				[b]Note:[/b] For better type safety, use [method clampf], [method clampi], [method Vector2.clamp], [method Vector2i.clamp], [method Vector3.clamp], [method Vector3i.clamp], [method Vector4.clamp], or [method Vector4i.clamp].
			</description>
		</method>
		<method name="clampf">
			<return type="float" />
			<param index="0" name="value" type="float" />
			<param index="1" name="min" type="float" />
			<param index="2" name="max" type="float" />
			<description>
				Clamps the [param value], returning a [float] not less than [param min] and not more than [param max].
				[codeblock]
				var speed = 42.1
				var a = clampf(speed, 1.0, 20.5) # a is 20.5

				speed = -10.0
				var b = clampf(speed, -1.0, 1.0) # b is -1.0
				[/codeblock]
			</description>
		</method>
		<method name="clampi">
			<return type="int" />
			<param index="0" name="value" type="int" />
			<param index="1" name="min" type="int" />
			<param index="2" name="max" type="int" />
			<description>
				Clamps the [param value], returning an [int] not less than [param min] and not more than [param max].
				[codeblock]
				var speed = 42
				var a = clampi(speed, 1, 20) # a is 20

				speed = -10
				var b = clampi(speed, -1, 1) # b is -1
				[/codeblock]
			</description>
		</method>
		<method name="cos">
